#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_hello_world" route name is not important yet
app_home_demandeur:
    path: /demandeur/home
    controller: App\Controller\DemandeurController::homeAction   
app_creerTicket_demandeur:
    path: /demandeur/creerTicket
    controller: App\Controller\DemandeurController::creerTicket
app_consulterTicket:
    path: /demandeur/consulterTicket
    controller: App\Controller\DemandeurController::consulterTicket
app_home_operateur:
    path: /operateur/home
    controller: App\Controller\OperateurController::homeAction
app_consulterTicket_operateur:
    path: /operateur/tickets
    controller: App\Controller\OperateurController::consulterTickets
app_home_responsable:
    path: /responsable/home
    controller: App\Controller\ResponsableController::homeAction
app_consulterStatistiques_responsable:
    path: /responsable/statistique
    controller: App\Controller\ResponsableController::consulterStatistiques